[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "urletra-controlclient"
version = "0.1.0"
description = "Remote controller TCP client library for certain feedback-loop simulations."
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["msgpack>=1.0"]
authors = [{name = "Andras Retzler", email = "randras@sdr.hu"}]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["urletra*"]
